package com.ruling_0.materiallib.examples;

import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import com.ruling_0.materiallib.MaterialLib;
import com.ruling_0.materiallib.api.MaterialLibAPI;
import com.ruling_0.materiallib.api.Shape;
import com.ruling_0.materiallib.api.TextureSet;

import cpw.mods.fml.common.registry.GameRegistry;

/// Temporary in-game verification of the four shape types: a `testGear` item shape, a `testFrame` block shape, a
/// `test` fluid shape, and a `testBucket` fluid-in-container shape, each generated by two materials, one tinted.
///
/// Registered from MaterialLib's own preInit so a dev `runClient` shows them in the creative tabs and NEI,
/// confirming icon binding, tint, display names (format and lang override), oredict, block placed metadata, fluid
/// registration, and the bucket-to-fluid mapping. The grayscale textures make the gold tint on `TestGold` obvious.
/// A shape consumer on `testGear` registers a shapeless recipe per material crafting its frame into its gear,
/// confirming consumer dispatch and per-material stacks in NEI.
public final class TempShapeExample {

    private TempShapeExample() {}

    public static void register() {
        TextureSet test = TextureSet.of(MaterialLib.MODID, "test");

        Shape testGear = MaterialLibAPI.newItemShape(MaterialLib.MODID, "testGear")
            .displayName("%s Gear")
            .oreDict("gear", "cog")
            .build();

        Shape testFrame = MaterialLibAPI.newBlockShape(MaterialLib.MODID, "testFrame")
            .displayName("%s Frame")
            .oreDict("frameGt")
            .build();

        Shape testFluid = MaterialLibAPI.newFluidShape(MaterialLib.MODID, "test")
            .displayName("Molten %s")
            .build();

        Shape testBucket = MaterialLibAPI.newFluidInContainerShape(MaterialLib.MODID, "testBucket")
            .fluid(testFluid)
            .displayName("%s Bucket")
            .emptyContainer(new ItemStack(Items.bucket))
            .oreDict("bucket")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestIron", test)
            .generateShapes(testGear, testFrame, testFluid, testBucket)
            .addTooltip("Iron strong")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestGold", test)
            .setTint(0xFFFFD700)
            .generateShapes(testGear, testFrame, testFluid, testBucket)
            .addTooltip("Shiny gold", "so shiny")
            .build();

        MaterialLibAPI.registerShapeConsumer(MaterialLib.MODID, testGear, (shape, material) -> {
            ItemStack gear = MaterialLibAPI.getStack(material, shape, 1);
            ItemStack frame = MaterialLibAPI.getStack(material, testFrame, 1);
            GameRegistry.addShapelessRecipe(gear, frame);
        });
    }
}
