package com.ruling_0.materiallib.examples;

import com.ruling_0.materiallib.MaterialLib;
import com.ruling_0.materiallib.api.MaterialLibAPI;
import com.ruling_0.materiallib.api.Shape;
import com.ruling_0.materiallib.api.TextureSet;

/// Temporary in-game verification of item and block shapes: a `testGear` item shape and a `testFrame` block shape,
/// each generated by two materials, one tinted.
///
/// Registered from MaterialLib's own preInit so a dev `runClient` shows both in the creative tabs, confirming icon
/// binding, tint, display names (format and lang override), oredict, and -- for the block -- placed metadata and
/// the wide metadata EndlessIDs provides. The grayscale textures make the gold tint on `TestGold` obvious.
/// Temporary scaffolding, removed when the full examples land.
public final class TempShapeExample {

    private TempShapeExample() {}

    public static void register() {
        TextureSet test = TextureSet.of(MaterialLib.MODID, "test");

        Shape testGear = MaterialLibAPI.newItemShape(MaterialLib.MODID, "testGear")
            .displayName("%s Gear")
            .oreDict("gear", "cog")
            .build();

        Shape testFrame = MaterialLibAPI.newBlockShape(MaterialLib.MODID, "testFrame")
            .displayName("%s Frame")
            .oreDict("frameGt")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestIron", test)
            .generateShapes(testGear, testFrame)
            .addTooltip("Iron strong")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestGold", test)
            .setTint(0xFFFFD700)
            .generateShapes(testGear, testFrame)
            .addTooltip("Shiny gold", "so shiny")
            .build();
    }
}
