package com.ruling_0.materiallib.examples;

import com.ruling_0.materiallib.MaterialLib;
import com.ruling_0.materiallib.api.MaterialLibAPI;
import com.ruling_0.materiallib.api.Shape;
import com.ruling_0.materiallib.api.TextureSet;

/// Temporary in-game verification of item shapes: a `testGear` item shape generated by two materials, one tinted.
///
/// Registered from MaterialLib's own preInit so a dev `runClient` shows the gears in the Materials creative tab,
/// confirming icon binding, tint, display names (format and lang override), and oredict. The grayscale gear
/// texture makes the gold tint on `TestGold` obvious. Temporary scaffolding, removed when the full examples land.
public final class TempItemShapeExample {

    private TempItemShapeExample() {}

    public static void register() {
        TextureSet test = TextureSet.of(MaterialLib.MODID, "test");

        Shape testGear = MaterialLibAPI.newItemShape(MaterialLib.MODID, "testGear")
            .displayName("%s Gear")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestIron", test)
            .generateShape(testGear)
            .addTooltip("Iron strong")
            .build();

        MaterialLibAPI.newMaterial(MaterialLib.MODID, "TestGold", test)
            .setTint(0xFFFFD700)
            .generateShape(testGear)
            .addTooltip("Shiny gold", "so shiny")
            .build();
    }
}
